version: '3.4'

services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.21.6
    ports:
      - 8080:8080
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'

  text-embeddings-inference:
    image: ghcr.io/huggingface/text-embeddings-inference:0.2.2
    ports:
      - 8081:80
    environment:
      MODEL: BAAI/bge-large-en-v1.5
      REVISION: main
    volumes:
      - ./data:/data
    command:
      - "--model-id"
      - "$MODEL"
      - "--max-batch-tokens"
      - "131072"
      - "--max-client-batch-size"
      - "64"
      - "--revision"
      - "$REVISION"
    runtime: nvidia

volumes:
  weaviate_data:
